# Konfiguracja Gitpod
image:
  file: .gitpod.Dockerfile

# Prekonfiguracja terminala
tasks:
  - name: Install Dependencies
    command: npm install

# Otwórz port 8080
ports:
  - port: 8080
    onOpen: ignore
