image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Update backend..."
      cd backend && \
      npm install && \

  - command: | 
      echo "Update frontend..." && \
      cd front && \
      npm install --save socket.io-client && \
      npm install && \
ports:
  - port: 3000
    visibility: public
  - port: 8080
    visibility: public
