image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Initializing backend..."
      cd backend
      node index.js
  
  - command: |
      echo "Initializing frontend..."
      cd front
      npm install --save socket.io-client
      export VUE_APP_SERVER_URL=$(gp url 3000)
      npm run serve
      gp preview $(gp url 8080)
ports:
  - port: 3000
    visibility: public
  - port: 8080
    visibility: public
