image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      echo "Run backend..."
      cd backend
      npm install
      node index.js
  - command: | 
      echo "Run frontend..."
      cd front
      npm install --save socket.io-client
      npm install
      npm run serve
  - command: gp preview 3000
ports:
  - port: 3000
    visibility: public
  - port: 8080
    visibility: public
