image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Initializing backend..."
      # Wprowadź tutaj odpowiednie polecenia do uzupełnienia .env
      sed -i 's/login_api=/login_api=example/' .env
      sed -i 's/password_api=/password_api=password/' .env
      sed -i 's/phone=/phone=123456789/' .env
      cd backend
      npm install
      node index.js
  
  - command: |
      echo "Initializing frontend..."
      cd front
      npm install --save socket.io-client
      export VUE_APP_SERVER_URL=$(gp url 3000)
      npm install
      npm run serve
      gp preview $(gp url 8080)
ports:
  - port: 3000
    visibility: public
  - port: 8080
    visibility: public
